from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeCarpBannerAssets: 


	# Image Rule Assets
	# 育成 
	I_SHI_GROWN_1 = RuleImage(roi_front=(572,272,21,33), roi_back=(530,220,202,267), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb1/cb1_shi_grown_1.png")
	# 结界卡 
	I_SHI_CARD_1 = RuleImage(roi_front=(911,262,20,33), roi_back=(823,210,252,297), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb1/cb1_shi_card_1.png")


	# Image Rule Assets
	# 育成 
	I_SHI_GROWN_2 = RuleImage(roi_front=(585,336,21,38), roi_back=(519,212,220,281), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb2/cb2_shi_grown_2.png")
	# 结界卡 
	I_SHI_CARD_2 = RuleImage(roi_front=(871,341,20,36), roi_back=(823,210,252,297), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb2/cb2_shi_card_2.png")


	# Image Rule Assets
	# 育成 
	I_SHI_GROWN_3 = RuleImage(roi_front=(600,277,19,34), roi_back=(519,212,220,281), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb3/cb3_shi_grown_3.png")
	# 结界卡 
	I_SHI_CARD_3 = RuleImage(roi_front=(899,281,21,40), roi_back=(823,210,252,297), threshold=0.6, method="Multi-scale template matching", file="./tasks/Component/CostumeCarpBanner/cb3/cb3_shi_card_3.png")


