from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AutoCheckinBigGodAssets: 


	# Image Rule Assets
	# 进去地藏像 
	I_KSITIGARBHA = RuleImage(roi_front=(6,380,31,33), roi_back=(0,278,485,314), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_ksitigarbha.png")
	# 进入通知 
	I_ACTIVITY_NOTICE = RuleImage(roi_front=(1093,480,42,75), roi_back=(1093,480,42,75), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_activity_notice.png")
	# 检测是否处于通知页 
	I_ACTIVITY_NOTICE_IN = RuleImage(roi_front=(600,65,74,38), roi_back=(600,65,74,38), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_activity_notice_in.png")
	# 进入大神福利中心 
	I_NOTICE_GOD = RuleImage(roi_front=(665,521,59,41), roi_back=(226,133,678,459), threshold=0.9, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_notice_god.png")
	# 检查是否在大神福利界面 
	I_NOTICE_GOD_IN = RuleImage(roi_front=(488,98,53,56), roi_back=(480,89,256,70), threshold=0.7, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_notice_god_in.png")
	# 领取奖励按钮 
	I_GOD_REWARD = RuleImage(roi_front=(650,209,99,42), roi_back=(638,184,119,405), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_god_reward.png")
	# 获取奖励成功,点击返回 
	I_GET_REWARD = RuleImage(roi_front=(476,211,29,60), roi_back=(468,181,89,98), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_get_reward.png")
	# 退出福利中心 
	I_GOD_EXIT = RuleImage(roi_front=(1055,190,44,36), roi_back=(1055,190,44,36), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_god_exit.png")
	# 退出地藏像界面 
	I_ACTIVITY_EXIT = RuleImage(roi_front=(1124,71,45,41), roi_back=(1124,71,45,41), threshold=0.8, method="Template matching", file="./tasks/AutoCheckinBigGod/res/res_activity_exit.png")


	# Swipe Rule Assets
	# 向下滑动找到大神福利 
	S_GOD_FIND = RuleSwipe(roi_front=(558,441,145,152), roi_back=(553,118,155,164), mode="default", name="god_find")
	# description 
	S_KSITIGARBHA_FIND = RuleSwipe(roi_front=(696,199,110,111), roi_back=(901,197,116,110), mode="vector", name="ksitigarbha_find")


